// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABodldH1v5SSxU-odiRN2_oTkXzTCQfcA',
    appId: '1:520770380974:web:607e6902956608a5da793f',
    messagingSenderId: '520770380974',
    projectId: 'flostay-ce499',
    authDomain: 'flostay-ce499.firebaseapp.com',
    storageBucket: 'flostay-ce499.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5HJBgiVfePyqazmZGQMxLnoo4CKJJk8c',
    appId: '1:520770380974:android:dec197c05daf3ed5da793f',
    messagingSenderId: '520770380974',
    projectId: 'flostay-ce499',
    storageBucket: 'flostay-ce499.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1EjMbxc3vtllx5v1sFLa8-bFPoX5H6k',
    appId: '1:520770380974:ios:15a3092b4063952cda793f',
    messagingSenderId: '520770380974',
    projectId: 'flostay-ce499',
    storageBucket: 'flostay-ce499.firebasestorage.app',
    iosBundleId: 'com.example.flostay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1EjMbxc3vtllx5v1sFLa8-bFPoX5H6k',
    appId: '1:520770380974:ios:15a3092b4063952cda793f',
    messagingSenderId: '520770380974',
    projectId: 'flostay-ce499',
    storageBucket: 'flostay-ce499.firebasestorage.app',
    iosBundleId: 'com.example.flostay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABodldH1v5SSxU-odiRN2_oTkXzTCQfcA',
    appId: '1:520770380974:web:a3759fbd89b09bc9da793f',
    messagingSenderId: '520770380974',
    projectId: 'flostay-ce499',
    authDomain: 'flostay-ce499.firebaseapp.com',
    storageBucket: 'flostay-ce499.firebasestorage.app',
  );
}
